const FETCHED_GAMES = 'FETCHED_GAMES'
const FETCHED_PLAYERS = 'FETCHED_PLAYERS'
const FETCHED_TEAMS = 'FETCHED_TEAMS'
const LOADING_GAMES = 'LOADING_GAMES'
const LOADING_PLAYERS = 'LOADING_PLAYERS'
const LOADING_TEAMS = 'LOADING_TEAMS'
const LOADING_STANDINGS = 'LOADING_STANDINGS'
const FETCHED_STANDINGS = 'FETCHED_STANDINGS'
const LOGGED_IN = 'LOGGED_IN'
const ADDED_COMMENT = 'ADDED_COMMENT'
const FETCHED_COMMENTS = "FETCHED_COMMENTS"
const LOADING_COMMENTS = 'LOADING_COMMENTS'
const DELETE_COMMENT = "DELETE_COMMENT"

export {FETCHED_GAMES, FETCHED_PLAYERS, FETCHED_TEAMS, LOADING_GAMES, LOADING_PLAYERS, LOADING_TEAMS, LOGGED_IN, FETCHED_STANDINGS, LOADING_STANDINGS, ADDED_COMMENT, FETCHED_COMMENTS, LOADING_COMMENTS, DELETE_COMMENT}